apiVersion: v1
kind: List
items:
- kind: ProjectRequest
  apiVersion: v1
  metadata:
    name: basic-wildfly-dev
    creationTimestam: null
  displayName: Basic wildfly App - Dev
- kind: ProjectRequest
  apiVersion: v1
  metadata:
    name: basic-wildfly-stage
    creationTimestam: null
  displayName: Basic wildfly App - Stage
- kind: ProjectRequest
  apiVersion: v1
  metadata:
    name: basic-wildfly-prod
    creationTimestam: null
  displayName: Basic wildfly App - Prod
- kind: ProjectRequest
  apiVersion: v1
  metadata:
    name: basic-wildfly-build
    creationTimestam: null
  displayName: Basic wildfly App - Build
